// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(
    key: 'centro_custo/list/centro_custo_list',
    uri: Uri.parse('centro_custo/list/centro_custo_list'),
    routeBuilder: b0Builder,
  ),
  RouteEntity(
    key: 'relatorios',
    uri: Uri.parse('relatorios'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: 'lancamentos/list/lancamentos',
    uri: Uri.parse('lancamentos/list/lancamentos'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: 'conta/list/conta_list',
    uri: Uri.parse('conta/list/conta_list'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: 'auth/login',
    uri: Uri.parse('auth/login'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: 'cartao/list/cartao_list',
    uri: Uri.parse('cartao/list/cartao_list'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(
    key: 'categoria/list/categoria_list',
    uri: Uri.parse('categoria/list/categoria_list'),
    routeBuilder: b6Builder,
  ),
  RouteEntity(key: 'home', uri: Uri.parse('home'), routeBuilder: b7Builder),
];

const routePaths = (
  path: '/',
  centroCusto: (
    path: '/centro_custo',
    list: (
      path: '/centro_custo/list',
      centroCustoList: '/centro_custo/list/centro_custo_list',
    ),
  ),
  relatorios: '/relatorios',
  lancamentos: (
    path: '/lancamentos',
    list: (
      path: '/lancamentos/list',
      lancamentos: '/lancamentos/list/lancamentos',
    ),
  ),
  conta: (
    path: '/conta',
    list: (path: '/conta/list', contaList: '/conta/list/conta_list'),
  ),
  auth: (path: '/auth', login: '/auth/login'),
  cartao: (
    path: '/cartao',
    list: (path: '/cartao/list', cartaoList: '/cartao/list/cartao_list'),
  ),
  categoria: (
    path: '/categoria',
    list: (
      path: '/categoria/list',
      categoriaList: '/categoria/list/categoria_list',
    ),
  ),
  home: '/home',
);
